### ISSUE TITLE
[Bug]: Grizzly doesn't see any SyntheticMonitoringChecks

### ISSUE THREAD

**Issue by asreich** [grafana/grizzly#388] opened 2024-03-14 17:46 UTC
### Grizzly Version

0.4.0

### Expected Behavior

We have configured 86 Synthetic Monitoring Checks via the UI and Grizzly should be able to find them and pull down a JSON representation of them as described [here](https://grafana.github.io/grizzly/synthetic-monitoring/)

### Actual Behavior

Grizzly finds 0 SyntheticMonitoringCheck resources

### Steps to Reproduce

```
export GRAFANA_URL=https://mycompany.grafana.net
export GRAFANA_TOKEN=<SNIP>

# Generate Access policy with metrics/logs read/write and stack:read
grr config set synthetic-monitoring.token <SNIP> # API key (must have MetricsPublisher permissions)
grr config set synthetic-monitoring.stack-id <SNIP>
grr config set synthetic-monitoring.metrics-id <SNIP>
grr config set synthetic-monitoring.logs-id <SNIP>

➜  ~/Downloads/grr-0.4.0 pull -d resources --output json -t SyntheticMonitoringCheck
Flag --directory has been deprecated, now it is inferred from the operating system
INFO[0000] Pulling resources to resources               
LibraryElement skipped
AlertRuleGroup skipped
AlertContactPoint skipped
PrometheusRuleGroup skipped
Datasource skipped
Dashboard skipped
AlertNotificationPolicy skipped
No resources found
Pulling 0 resources
DashboardFolder skipped
```

**Comment by julienduchesne** [comment] 2024-04-03 11:50
Probably a duplicate of https://github.com/grafana/grizzly/issues/216

**Comment by asreich** [comment] 2024-04-03 23:28
Yeah, after reviewing [this](https://grafana.com/docs/grafana-cloud/monitor-public-endpoints/set-up/set-up-private-probes/#probe-api-server-url) page and comparing the hardcoded address to the us-east endpoint, that seems accurate. Feel free to close this in favor of the prior if you like.

**Comment by spinillos** [comment] 2024-04-22 09:48
`grr config set synthetic-monitoring.url` was added to set your own URL.

**Closed by spinillos** 2024-04-22 09:48 UTC
Labels: bug, triage
