### ISSUE TITLE
Grizzly always thinks dashboards differ by folder, id and version

### ISSUE THREAD

**Issue by rhowe** [grafana/grizzly#131] opened 2021-07-01 10:09 UTC
I'm using grizzly from master (13e1c3b71a248d27b70b34f2dd38d5faedd5f195) and it always wants to apply changes to the dashboards I'm generating with grafonnet. This is against Grafana 8.0.2.

`grr diff` shows the following deltas:

`metadata/folder` is the folder name at the remote, but the folder id locally (should I be using the folder name in the dashboard resource?)

In the dashboard JSON itself, locally I have `id: null` and `version: 0` but the "remote" has neither of these attributes.

This means that grizzly always applies updates, even if the dashboard hasn't really changed. Not sure whether to call this a grizzly or grafonnet issue, but I thought I'd try grizzly first.

**Comment by dsotirakis** [comment] 2021-07-02 10:37
Hello @rhowe, thanks for raising the issue - could you please try and use the latest master and check if the issue is still there?
We merged this 2 days ago #128 and should have fixed some issues. Let me know once you try so we can fix it :)

**Comment by rhowe** [comment] 2021-07-02 10:48
With the code from `master`, grizzly no longer thinks the `metadata/folder` has changed, but it still wants to add `id: 0` and `version: 0`
Also, for a folder, `grr diff` shows the following as being present at the remote, but not locally (which is true - I'm not setting any of those things explicitly):

```
canAdmin
canEdit
canSave
created
createdBy
hasAcl
id
updated
updatedBy
url
version
```

**Comment by malcolmholmes** [comment] 2024-04-11 21:24
So much has changed since this issue was opened. Closing as done. Please re-open if not yet working.

**Comment by marioanton** [comment] 2024-04-16 21:21
Please reopen, still same issue.

**Comment by malcolmholmes** [comment] 2024-05-01 08:33
@marioanton can you give more details? What version are you using? Can you give an example of the diff you're seeing? I'll need a bit more if I'm going to reproduce your issue.

**Comment by malcolmholmes** [comment] 2024-05-21 12:33
Closing, please reopen with more details if still happening.

**Closed by malcolmholmes** 2024-05-21 12:33 UTC
